package views;

import modelo.Medico;
import modelo.Paciente;
import views.helper.MedicoPesquisaJDialog;
import views.helper.PacientePesquisaJDialog;
import views.utils.BaseFormulario;


public class AgendamentoView extends BaseFormulario {

    private Medico medicoSelecionado;
    private Paciente pacienteSelecionado;
    /**
     * Creates new form AgendamentoView
     */
    public AgendamentoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSelecioneProfissional = new javax.swing.JLabel();
        txtNomeMedico = new javax.swing.JTextField();
        lbPacienteName = new javax.swing.JLabel();
        txtNomePaciente = new javax.swing.JTextField();
        btnBuscarMedico = new javax.swing.JButton();
        btnBuscarPaciente = new javax.swing.JButton();
        lbHorarios = new javax.swing.JLabel();
        lbTituloCRM = new javax.swing.JLabel();
        lbCRM = new javax.swing.JLabel();
        lbEspecialidade = new javax.swing.JLabel();

        setTitle("Agendamento de Consultas");

        lbSelecioneProfissional.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        lbSelecioneProfissional.setText("Selecione Profissional*");

        txtNomeMedico.setEditable(false);

        lbPacienteName.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        lbPacienteName.setText("Paciente*");

        txtNomePaciente.setEditable(false);

        btnBuscarMedico.setText("...");
        btnBuscarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMedicoActionPerformed(evt);
            }
        });

        btnBuscarPaciente.setText("...");
        btnBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPacienteActionPerformed(evt);
            }
        });

        lbHorarios.setText("Horários disponíveis");

        lbTituloCRM.setText("CRM:");

        lbCRM.setText("::::");

        lbEspecialidade.setText(":::");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTituloCRM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCRM)
                        .addGap(138, 138, 138)
                        .addComponent(lbEspecialidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSelecioneProfissional)
                            .addComponent(lbPacienteName)
                            .addComponent(txtNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbHorarios)
                            .addComponent(txtNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarMedico)
                            .addComponent(btnBuscarPaciente))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSelecioneProfissional)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarMedico)
                    .addComponent(txtNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTituloCRM)
                    .addComponent(lbCRM)
                    .addComponent(lbEspecialidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPacienteName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbHorarios)
                .addContainerGap(295, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMedicoActionPerformed
        MedicoPesquisaJDialog medicoPesquisaJDialog=new MedicoPesquisaJDialog(null, true);
        medicoPesquisaJDialog.setVisible(true);
        medicoSelecionado = medicoPesquisaJDialog.getMedicoSelecionado();
        if(medicoSelecionado != null && medicoSelecionado.getId() != null){
            txtNomeMedico.setText(medicoSelecionado.getNome().toUpperCase());
            lbCRM.setText(medicoSelecionado.getCRM());
            lbEspecialidade.setText(medicoSelecionado.getEspecializacao());
        }else{
            limpar();
        }
    }//GEN-LAST:event_btnBuscarMedicoActionPerformed

    private void btnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPacienteActionPerformed
       PacientePesquisaJDialog pacientePesquisaJDialog=new PacientePesquisaJDialog(null, true);
        pacientePesquisaJDialog.setVisible(true);
        pacienteSelecionado = pacientePesquisaJDialog.getPacienteSelecionado();
        if(pacienteSelecionado != null && pacienteSelecionado.getId() != null){
            txtNomePaciente.setText(pacienteSelecionado.getNome().toUpperCase());
        }else{
            
        }        
    }//GEN-LAST:event_btnBuscarPacienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarMedico;
    private javax.swing.JButton btnBuscarPaciente;
    private javax.swing.JLabel lbCRM;
    private javax.swing.JLabel lbEspecialidade;
    private javax.swing.JLabel lbHorarios;
    private javax.swing.JLabel lbPacienteName;
    private javax.swing.JLabel lbSelecioneProfissional;
    private javax.swing.JLabel lbTituloCRM;
    private javax.swing.JTextField txtNomeMedico;
    private javax.swing.JTextField txtNomePaciente;
    // End of variables declaration//GEN-END:variables

    private void limpar() {
        lbCRM.setText(":::");
        lbEspecialidade.setText(":::");
        txtNomeMedico.setText(null);
    }
}
